package Hibernate;
// Generated 5 f�vr. 2019 11:18:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private BigDecimal id;
     private String contenu;
     private String emetteur;
     private Date dateEnvoi;

    public Message() {
    }

	
    public Message(BigDecimal id) {
        this.id = id;
    }
    public Message(BigDecimal id, String contenu, String emetteur, Date dateEnvoi) {
       this.id = id;
       this.contenu = contenu;
       this.emetteur = emetteur;
       this.dateEnvoi = dateEnvoi;
    }
   
    public Message(String contenu, String emetteur, Date dateEnvoi) {
       this.contenu = contenu;
       this.emetteur = emetteur;
       this.dateEnvoi = dateEnvoi;
    }
    
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }
    public String getEmetteur() {
        return this.emetteur;
    }
    
    public void setEmetteur(String emetteur) {
        this.emetteur = emetteur;
    }
    public Date getDateEnvoi() {
        return this.dateEnvoi;
    }
    
    public void setDateEnvoi(Date dateEnvoi) {
        this.dateEnvoi = dateEnvoi;
    }




}


