package Hibernate;
// Generated 5 févr. 2019 11:18:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private BigDecimal id;
     private String identifient;
     private String motDePasse;

    public Utilisateur() {
    }

	
    public Utilisateur(BigDecimal id) {
        this.id = id;
    }
    public Utilisateur(BigDecimal id, String identifient, String motDePasse) {
       this.id = id;
       this.identifient = identifient;
       this.motDePasse = motDePasse;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getIdentifient() {
        return this.identifient;
    }
    
    public void setIdentifient(String identifient) {
        this.identifient = identifient;
    }
    public String getMotDePasse() {
        return this.motDePasse;
    }
    
    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }




}


